### ISSUE TITLE
[Bug]: Unable to change Distilled CFG scale schedule

### ISSUE THREAD

**Issue by asdrabael** [Tok/sd-forge-deforum#3]
### What happened and why was it ungood?

I've noticed that it starts on 3.5, but no matter what number you put it on when it's rendering in the cmd window, it always stays on 3.5 and can't be changed. You can change the regular CFG or schedule it to change like everything else, but not the flux CFG.

edit: Ok, playing with it changing the value does actually effect the results but it just doesn't change the displayed number in the cmd window. like setting the DCFG to 1 gives an extremely obvious and large change from 3.5

**Comment by Tok** [comment]
Thanks for reporting the bug. I just pushed an update that should fix it.

Before there were two different schedule sets for CFG scheduling:
* One directly on the "Run" tab, meant for img2img
* Another one in the "Keyframes" - "CFG" sub-tab meant for txt2img only

This was rather confusing and didn't make a lot of sense, so values have been mixed up and confused somewhere along the way.

The two scale schedules are now unified and forwarded to both pipes:
* The the separate scale schedules on the "Run" have been removed.
* The CFG and distilled CFG schedules on the "CFG" tab are now controlling both pipes (img2img and txt2img on 1st frame).

Here's the commit:
https://github.com/Tok/sd-forge-deforum/commit/4db2cfa7b922e7ef05e2817b43a5c769126410bd
