### ISSUE TITLE
[Feature Request]: keyframe distribution --> ValueError: Invalid keyframe_distribution from UI: None

### ISSUE THREAD

**Issue by asdrabael** [Tok/sd-forge-deforum#6]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

Have it start in the Off position instead of no selection at all. I kept getting errors and couldn't figure out what keyframe issue i was having until i realized that when I started it up the keyframe distribution starts with no options selected at all and something has to be picked for it to run.

### Proposed workflow

1. Start Forge
2. Press the deforum tab
3. profit

### Additional information

that's pretty much it

### Are you going to help adding it?

i wish, but that's outside my skillset

**Comment by Tok** [comment]
Hi, 

Keyframe distribution has actually been implemented already.
If you update the extension to the latest version in Forge, you should see a new subtab "Distribution" under the "Keyframes" tab, with explanations and recommendations on how to use it.

I would recommend you try to generate the Default Bunny with the new default settings which you can find at:
https://github.com/deforum-art/sd-webui-deforum/blob/automatic1111-webui/scripts/default_settings.txt
It's basically generating an audio-synchronized 5 second clip directly at 60 FPS, but only performs diffusions at the frames defined in "prompts".

**Comment by asdrabael** [comment]
> Hi,
> 
> Keyframe distribution has actually been implemented already. If you update the extension to the latest version in Forge, you should see a new subtab "Distribution" under the "Keyframes" tab, with explanations and recommendations on how to use it.
> 
> I would recommend you try to generate the Default Bunny with the new default settings which you can find at: https://github.com/deforum-art/sd-webui-deforum/blob/automatic1111-webui/scripts/default_settings.txt It's basically generating an audio-synchronized 5 second clip directly at 60 FPS, but only performs diffusions at the frames defined in "prompts".

I know, i have it. the issue is that when you go to deforum the Keyframe Distribution dropdown menu starts with no selection at all rather than on the Off selection forcing you to go to the tab and select Off.

**Comment by Tok** [comment]
True. This is currently an issue. I will look into it when I find time.

Meanwhile, there is an easy workaround:
- When starting for the 1st time, select a keyframe distribution like "off".
- Save settings and optionally update Forge defaults.
